---
- name: Add redis PPA (Ubuntu)
  apt_repository: repo='ppa:rwky/redis'
                  update_cache=yes
  when: ansible_lsb.id == "Ubuntu"
  tags:
    - install
    - redis
    - deps

- name: Install redis server
  apt: pkg=redis-server
  tags:
    - install
    - redis
    - deps

- name: Make sure redis is running
  service:  name=redis-server
            state=started
  tags:
    - install
    - redis
    - deps
